/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as JobCreateSchemas_companies from "../JobCreateSchemas/companies.js";
import type * as JobCreateSchemas_jobPosting from "../JobCreateSchemas/jobPosting.js";
import type * as JobGetNullScores_JobCompanyConnect from "../JobGetNullScores/JobCompanyConnect.js";
import type * as JobGetNullScores_getNull from "../JobGetNullScores/getNull.js";
import type * as UserCreateSchemas_details from "../UserCreateSchemas/details.js";
import type * as UserCreateSchemas_education from "../UserCreateSchemas/education.js";
import type * as UserCreateSchemas_experiences from "../UserCreateSchemas/experiences.js";
import type * as UserCreateSchemas_projects from "../UserCreateSchemas/projects.js";
import type * as UserCreateSchemas_resume from "../UserCreateSchemas/resume.js";
import type * as UserCreateSchemas_skills from "../UserCreateSchemas/skills.js";
import type * as UserCreateSchemas_user from "../UserCreateSchemas/user.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "JobCreateSchemas/companies": typeof JobCreateSchemas_companies;
  "JobCreateSchemas/jobPosting": typeof JobCreateSchemas_jobPosting;
  "JobGetNullScores/JobCompanyConnect": typeof JobGetNullScores_JobCompanyConnect;
  "JobGetNullScores/getNull": typeof JobGetNullScores_getNull;
  "UserCreateSchemas/details": typeof UserCreateSchemas_details;
  "UserCreateSchemas/education": typeof UserCreateSchemas_education;
  "UserCreateSchemas/experiences": typeof UserCreateSchemas_experiences;
  "UserCreateSchemas/projects": typeof UserCreateSchemas_projects;
  "UserCreateSchemas/resume": typeof UserCreateSchemas_resume;
  "UserCreateSchemas/skills": typeof UserCreateSchemas_skills;
  "UserCreateSchemas/user": typeof UserCreateSchemas_user;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
